### Set up webhook
PUT https://{{domain}}/api/telegram/webhook

### Check webhook status
GET https://{{domain}}/api/telegram/webhook

### Agenda
GET https://{{domain}}/api/telegram/agenda

### Week Plan
GET https://{{domain}}/api/telegram/week-plan
