### Set up webhook
PUT https://{{domain}}/hive/api/telegram/webhook

### Check webhook status
GET https://{{domain}}/hive/api/telegram/webhook

### Send agenda
GET https://{{domain}}/hive/api/telegram/agenda
